### ISSUE TITLE
4K Movie Posters Disappear or Do not Complete the Scan

### ISSUE THREAD

**Issue by russellmoran99** [jkirkcaldy/plex-utills#102]
@jkirkcaldy Hey man, appreciate all the hard work.  I've had an issue for a while and decided to manually "fix it" but now it's messing up more and more often.  The problem is when it's scanning my 4K movie libraries and it finds a new movie, it will some times work, sometimes it leave me with half a picture and sometimes it's blank.

My previous fix would be go to edit the poster and change it to a 4K version.  Sometimes it would stay, sometimes it would revert back to a black empty poster or half a scanned poster.  See screenshots attached.  Thanks for any help
![Capture](https://user-images.githubusercontent.com/58992321/159335439-25e1c706-bf28-4d8a-8f7e-d504068e7605.PNG)
![Capture2](https://user-images.githubusercontent.com/58992321/159335451-693eeefe-9e87-4064-b469-ae635dde035a.PNG)
.

**Comment by bhoffmann84** [comment]
I am experiencing the same problems.

Some posters return to blank even after manually selecting a version with 4K banners. Some only show half the image.

I´m running plex-utills as a docker container on unraid (all latest versions). It worked fine until a few months ago and is seemingly getting worse.




![2022-03-24 11_16_22-Plex](https://user-images.githubusercontent.com/74202150/159894649-d19f7c51-5a8a-4e08-ada3-8166fac39387.png)
![2022-03-24 11_19_00-Plex](https://user-images.githubusercontent.com/74202150/159895088-6e8d8f19-f653-49a6-87bd-fa656416972f.png)

**Comment by russellmoran99** [comment]
@jkirkcaldy @bhoffmann84  Same setup here.  Unraid on all latest versions and it worked great as until a few months ago.

**Comment by russellmoran99** [comment]
@jkirkcaldy I have not seen him on in a while.  Does anyone know if he is ok?

**Comment by minititof** [comment]
Pretty much the same issue, new movie posters are almost always incomplete.

![image](https://user-images.githubusercontent.com/7428385/164172848-4f4c286d-82ac-40af-a4bd-66b0a85bde7d.png)

**Comment by jkirkcaldy** [comment]
working on a fix now

**Comment by russellmoran99** [comment]
Where have you been?  Is everything ok?  


Sent from AT&T Yahoo Mail for iPhone


On Thursday, May 12, 2022, 7:59 AM, jkirkcaldy ***@***.***> wrote:




working on a fix now

**Comment by jkirkcaldy** [comment]
All good. Work just got super busy for a while.

**Comment by adznon** [comment]
Having the same problem, also same setup. Docker in UNRaid,

Mine also stops at a certain point again not going through all the movies I have.

**Comment by mallen012** [comment]
Any updates here, seems I am getting more of the same issue as above.

**Comment by jkirkcaldy** [comment]
Testing a fix for this now. 

Changed the way that posters are downloaded. The script should also check the posters are valid before adding banners and then once again before uploading them.

**Comment by tchirou** [comment]
Hello
Would you have any ETA about the fix going into the master branch ? 
Many thanks

**Comment by jkirkcaldy** [comment]
I'm testing it still. There are some big updates coming that should hopefully make it better for everyone. 

No definitive ETA yet but It's close

**Comment by jkirkcaldy** [comment]
Should be solved now.
