### ISSUE TITLE
File path and library issues?

### ISSUE THREAD

**Issue by DevXen** [jkirkcaldy/plex-utills#104]
So this isn't working. And my best guess is cause it's an issue with my directory structure.

I don't have a "Plex" directory. I have 2 separate root folders. One for movies and one for television.

Then each beyond that ia organized as well.

Television/Type of show/Genre/show name/season/files of the season.

Example:
Television/Live Action/Drama/Breaking Bad/[2008] - Season 01/Breaking Bad - S01E01 - Pilot (extra info on filename showing codecs and other misc things as applicable.)

....
Movies are..

Movies/SD or HD/Type of movie/Genre/movie name.

So my 3D movies are in:
Movies/HD/3D/Live Action/Action/Avatar (year) (3D-SBS) (other misc info in the file name.)

Apart from that possibly causing an issue. 
I did have to turn force secure connections off for it to even connect to my Plex. 

But I also have multiple libraries.

I have one for US movies, and foreign movies and one for ive action and one for documentaries and one for animated movies.

Same with my TV shows. I have separate libraries for US shows, Foreign Shows, Science shows, Documentaries, etc.

Which also Seems to be an issue as you can only choose one for movies, one for TV shows and one for 3D movies.

**Comment by jkirkcaldy** [comment]
You can have up to 10 separate film libraries. 

These should be a comma separated list in the config page, e.g.: `films,movies,other films`
