### ISSUE TITLE
Unable to use Hostnames in URL

### ISSUE THREAD

**Issue by 0mni** [jkirkcaldy/plex-utills#109]
I am unable to use hostnames in the URL for Plex and Tautulli.

I can only use:

http://192.168.1.1:32400

I can't use:

http://plex:32400

**Comment by JigSawFr** [comment]
@0mni Please take also a look in https://github.com/jkirkcaldy/plex-utills/issues/97#issuecomment-1120210036

**Comment by 0mni** [comment]
> @0mni Please take also a look in [#97 (comment)](https://github.com/jkirkcaldy/plex-utills/issues/97#issuecomment-1120210036)

Thanks! Will test it out.

**Comment by jkirkcaldy** [comment]
This is now fixed in the latest :dev container

`http://container:port` should now work
