### ISSUE TITLE
Plex-utills path

### ISSUE THREAD

**Issue by bchilton9** [jkirkcaldy/plex-utills#115]
I’m on the dev branch
It’s seems like it’s replacing all the forward slash with /films
I tried changing the Plex-Utills file path in the admin config to just / and it didn’t change the help page

I’m getting file not found errors

/filmsmovies/filmsVacation (2015)/filmsVacation 2015.mkv
--
This is the path where Plex-Utills expects to see your media sees your media. (Plex-Utills can see this file: False)

**Comment by frankdavalos** [comment]
Same issue, I'm pulling latest from unraid apps.  

plex-utills - [Errno 2] No such file or directory: '/films/media/4k_movies/Movie_Name (2022)/poster_bak.png'

My plex path is /data

**Comment by jkirkcaldy** [comment]
Should be solved on the :latest branch now.

**Comment by KrunchMuffin** [comment]
I seem to still be having this issue on :latest

**Comment by alexricher** [comment]
> I seem to still be having this issue on :latest

Same here. Whatever I change in the config, it's never finding my path to the files. Is there anything I should do to my config to fix this?
