### ISSUE TITLE
Windows 10 FileNotFoundError while running 4k Posters

### ISSUE THREAD

**Issue by rowdya22** [jkirkcaldy/plex-utills#116]
Installed docker on Windows and been getting errors. I am totally new to docker.....

`docker run -d -p 5000:5000 -v "M:/Plex" -v "C:/Plex Data/Plex Media Server/Logs" -e TZ=America/Denver -e PUID=1000 -e PGUI=1000 jkirkcaldy/plex-utills`

Unsure if the paths are correct for docker but this is what I'm running. Again, I am totally new to docker.....

Content is in M:\Plex and PMS Logs C:\Plex Data\Plex Media Server\Logs. After reading lots of issues I changed from \ paths to /. 

Web GUI loads and help page shows the first file properly:
![image](https://user-images.githubusercontent.com/19266317/195416460-dac855e7-2b34-48c9-b019-4a11d47c055d.png)

> IndexError: list index out of range
> 2022-10-12 12:01:49,124 - SYS - 4K/HDR Posters schedule created for 07:00
> 2022-10-12 12:01:49,124 - SYS - 4K/HDR Posters schedule created for 07:00
> 2022-10-12 12:01:49,125 - SYS - Hide 4k schedule created for 07:00
> 2022-10-12 12:01:49,125 - SYS - Hide 4k schedule created for 07:00
> 2022-10-12 12:01:49,125 - SYS - Auto Collections schedule created for 07:00
> 2022-10-12 12:01:49,125 - SYS - Auto Collections schedule created for 07:00
> [2022-10-12 12:02:04,579] ERROR in app: Exception on /admin_config [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "/app/app/routes.py", line 294, in admin_config_form
>     update_scheduler()
>   File "/app/app/__init__.py", line 141, in update_scheduler
>     plexpath = '/'+filepath.split('/')[1]
> IndexError: list index out of range
> 2022-10-12 12:03:09,933 - plex-utills - 4k Posters: 4k HDR poster script starting now.
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.9/threading.py", line 910, in run
>     self._target(*self._args, **self._kwargs)
>   File "/app/app/scripts.py", line 1184, in posters4k
>     m = MediaInfo.parse(file, output='JSON')
>   File "/usr/local/lib/python3.9/site-packages/pymediainfo/__init__.py", line 494, in parse
>     raise FileNotFoundError(filename)
> FileNotFoundError: M:\Plex\4K Movies\Alita - Battle Angel (2019)\Alita - Battle Angel (2019) [imdb-tt0437086] ([2160p BluRay][MLP 7.1][HEVC]) {edition-4K}.mkv

I have tried editing the Plex Path as I have seen in other solutions for the FileNotFoundError but each time I get a 500 error on the admin_config page.

My setup has multiple library folders in M:/Plex/ and I am unsure how to proceed.

**Comment by TheEvilMonkey** [comment]
Were you ever able to get this to work?  I'm also totally new to Docker on Windows and trying to figure out the right way to run this.

**Comment by jkirkcaldy** [comment]
If M: is a shared drive then there is a different way of mounting those. 

There is an example docker compose file for Windows here now: https://github.com/jkirkcaldy/plex-utills/wiki/Running-on-Windows
