### ISSUE TITLE
QNAP - Running script with HDR on

### ISSUE THREAD

**Issue by theroninhunter** [jkirkcaldy/plex-utills#117]
so ls /films in the console returns the correct directory BUT when I run the script with HDR enabled I can see this in the console

# ls /films
'Alita - Battle Angel (2019).mkv'                                'Indiana Jones And The Last Crusade (1989).mkv'           'Star Wars Episode V  The Empire Strikes Back (1980) .mkv'
'Ant-Man (2015).mkv'             

2022-10-21 22:09:19,967 - plex-utills - 4k Posters: 4k HDR poster script starting now.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app/scripts.py", line 1184, in posters4k
    m = MediaInfo.parse(file, output='JSON')
  File "/usr/local/lib/python3.9/site-packages/pymediainfo/__init__.py", line 494, in parse
    raise FileNotFoundError(filename)
FileNotFoundError: /films/CE_CACHEDEV1_DATA/Video/Movies/4K/Alita - Battle Angel (2019).mkv

**Comment by theroninhunter** [comment]
Settings

Enable the global 4K Poster script
True
Enable Dolby Atmos and DTS:X labels on the posters
False
Enable 4K Posters For Films
True
Enable 4K Posters For TV Shows
False
Select Mini 4k Posters
False
Enable HDR Banners
True
Use the new HDR Banners
True
Recreate HDR banners to use the Dolby Vision and HDR 10 banners
True
Enable 3D Poster script
False
Select Mini 3D posters
False

**Comment by jkirkcaldy** [comment]
It can't find your media. It could be a mounting issue. 

The default behaviour is to now fall back to using the metadata from plex. The downside to this is that it can only tell if it is HDR or Dolby Vision, so hdr10+ banners don't work. Also audio banners won't work when it can't scan the media.
