### ISSUE TITLE
QNAP - Poster backup - No such file or directory

### ISSUE THREAD

**Issue by theroninhunter** [jkirkcaldy/plex-utills#118]
Getting the below error for each 4K film in the films directory when backup is enabled

2022-10-21 21:59:38,718 - plex-utills - Batman Begins - Posters: Creating a backup file
2022-10-21 21:59:38,718 - plex-utills - [Errno 2] No such file or directory: '/films/CE_CACHEDEV1_DATA/Video/Movies/4K/poster_bak.png'

**Comment by theroninhunter** [comment]
I can create a file in the /film folder from terminal without any errors

**Comment by jkirkcaldy** [comment]
New update coming later will remove the need for this. Backups will be stored next you your config files removing the need for write permissions for your media directories.

**Comment by jkirkcaldy** [comment]
Solved with latest update. Backups are now stored in your config directory.
