### ISSUE TITLE
Simple Directions to run in Windows?

### ISSUE THREAD

**Issue by TheEvilMonkey** [jkirkcaldy/plex-utills#121]
Would really like some basic directions on how to run this in Windows if possible.  I have Docker installed and have the image downloaded but struggle with trying to figure out how to start it properly (along with the proper paths).

Thanks!

**Comment by jkirkcaldy** [comment]
I'm going to push a massive update to the main branch today that will make things easier. Including easier support for windows. 

There will be a new docker-compose template with windows specific settings that should get you started.

**Comment by jkirkcaldy** [comment]
https://github.com/jkirkcaldy/plex-utills/wiki/Running-on-Windows
