### ISSUE TITLE
Multiple copies of posters with each 4k_hdr_poster.py run

### ISSUE THREAD

**Issue by djnield** [jkirkcaldy/plex-utills#13]
I doubt this is the normal behaviour but each time I run the poster script an additional copy of the 4k poster is generated. Consequently each film has 5 or 6 4k posters so far.

Have I misconfigured or missed a step perhaps?

**Comment by jkirkcaldy** [comment]
No, this is the way it works at the moment, I'm looking into a way of figuring out if the poster already has a banner that way it won't create the banners again but the only way to stop that behaviour at the moment is to use the backup feature, as it will skip posters that have been backed up.

**Comment by jkirkcaldy** [comment]
The newest script will check to see whether the banners have been added and will no longer create new posters if the banners exist.

**Comment by djnield** [comment]
Yes the latest version is now skipping over previous banners thanks :)

But a new error has been introduced `FileNotFoundError: [Errno 2] No such file or directory: 'poster.png'`
This gets stuck in the same place each time (ironically at the B alphabet) and won't continue further.

**Comment by jkirkcaldy** [comment]
Does this happen for the same movie every time? 

Does it give any errors when it ends? I sometimes get timeout errors if I use a url rather than an IP address.

**Comment by djnield** [comment]
Yes it does and here's what I witnessed past few days.

I check the file it errors on and sure enough find it's missing a poster and showing blank. I add the poster back (and the 4k banner poster is an option to choose) and run the script and it happily completes. So I first make sure there's no blanks and the script finishes great.

Few days later I rerun the script to pick up new additions. Those same files from before have lost their posters again?

Can't work out what's happening there.

**Comment by jkirkcaldy** [comment]
I am not sure how, but it sounds like there are no posters assigned for the films that the script is having issues with. 

I have added some error handling now, so the script should continue if there is an error and show any posters that are not created in red. 

This way if there is an issue with the films, it will be highlighted and then you can go back through and see what, if any,  the issue is with the film.

**Comment by djnield** [comment]
Error checking sounds like a great addition. I'll check this shortly thanks.
