### ISSUE TITLE
DVD or BluRay options

### ISSUE THREAD

**Issue by Medwynd** [jkirkcaldy/plex-utills#16]
This is a great project.  I was thinking of doing this a long time ago but never had a chance to.  I still have a lot of older DVD content.  Would it be possible to have an option to add the dvd disc icon (the silver disc) and perhaps a bluray icon (same disc but blue).

Thanks

Edit: Wanted to label this as a request but couldnt quite figure out how.

**Comment by jkirkcaldy** [comment]
In theory that would be pretty easy. 

I'll have a look at the implementation.

**Comment by Zero0Q** [comment]
I love this Feature Request, yes please.

**Comment by jkirkcaldy** [comment]
For this, would every 1080p film be labeled as blueray? Same with dvd/sd options?

**Comment by Zero0Q** [comment]
DVD resolution everything less than 720p

Blu-ray is 720p, 1080i, 1080p

**Comment by wgstarks** [comment]
> DVD resolution everything less than 720p
> 
> Blu-ray from 720p, 1080i, 1080p
> 
> 4K from 2160p up to 8k

How would you know that it’s not a 1080p web download or a dvr copy off an hdtv stream? I have a huge number of 1080p videos that are not ripped from a bluray disk.

**Comment by jkirkcaldy** [comment]
This is the issue. Which is why I suggested a bitrate cut off. However not every Bluray is created equally so there may be some missed. I would argue that anything lower than 1080p/i wouldn't be bluray too. 

Some people add Bluray to their naming convention but not everyone so again a lot could get missed. 

It would be easy to create an SD banner as everything lower than 720p could be labeled as SD.

**Comment by wgstarks** [comment]
> This is the issue. Which is why I suggested a bitrate cut off. However not every Bluray is created equally so there may be some missed. I would argue that anything lower than 1080p/i wouldn't be bluray too.
> 
> Some people add Bluray to their naming convention but not everyone so again a lot could get missed.
> 
> It would be easy to create an SD banner as everything lower than 720p could be labeled as SD.

Agreed. And perhaps a translucent/opacity setting with the banners so that the poster can still be seen underneath. My concern is that a large portion of the poster is being blocked by all the banners and logos.

**Comment by Zero0Q** [comment]
Would you be better adding options so we can choose what we would like to be in each of those posters.
Exemple: there’s a Three option:
“BLURAY” “DVD” “SD” inside you can click what you want to chose like Blu-rays, HDTV, WEBDL, WEBRip,dvd,dvdrips,  
Let us decide what belongs in those options.

**Comment by jkirkcaldy** [comment]
But then there are the same issues? How do you differentiate between them if all that data is stripped from the file name. 

If you have a film titled as `title (2022)/title (2022).mkv` there is no way to tell what the quality is of that film. 

You can see the resolution and you can see the bitrate and that's about all you could use to figure it out. 

I'm hesitant to use file names for filtering as not everyone uses this method. I started to but there is a huge backlog of films with zero quality details in the file names. 

I think the best way forward would be to use a bitrate cutoff and then let the user state what that bitrate would be. Or perhaps both, if a file name contains Blu-ray, remux, bd _or_ meets the bitrate cutoff label as Blu-ray. 

Dvd would be anything less than 720p

**Comment by Zero0Q** [comment]
You can check how is kodi doing it

**Comment by wgstarks** [comment]
Perhaps a bitrate cutoff with the ability to manually set the quality if needed. Similar to Radarr/Sonarr.

**Comment by sdamaged99** [comment]
All my Blu-ray movies are in a folder called the same.  So everything in there is a blu ray remux file, so for my use case it's pretty easy.  Anything that's not a blu ray rip i wouldn't personally class as Blu-ray.  Every movie i have is named like "Alien (1979) Remux-1080p (for the Blu-ray) or Alien (1979) Remux-2160p (for the 4k disc)

**Comment by JamesDAdams** [comment]
Hi, it's an abandoned feater ?
