### ISSUE TITLE
No '4klibrary.py' script?

### ISSUE THREAD

**Issue by Silentbob101** [jkirkcaldy/plex-utills#21]
Have been following the manual install instruction...

the last step says 

Run the script. 
`python3 4klibrary.py'

where can I find this script ? I see no '4klibrary.py' script in the folder

**Comment by jkirkcaldy** [comment]
I think I renamed the script.    
  

  
For the posters it’s called 4k_hdr_poster.py
  

  
  
  
    
  

  
  
>

**Comment by Silentbob101** [comment]
Thought that might be the case, thanks for confirming... when I run '4k_hdr_poster.py' I hit this error 

`MacMiniServer:plex-utills chris$ python3 4k_hdr_poster.py 
Traceback (most recent call last):
  File "4k_hdr_poster.py", line 23, in <module>
    server = config_object["PLEXSERVER"]
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'PLEXSERVER'
MacMiniServer:plex-utills chris$ python3 4k_hdr_poster.py 
Traceback (most recent call last):
  File "4k_hdr_poster.py", line 23, in <module>
    server = config_object["PLEXSERVER"]
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'PLEXSERVER'
MacMiniServer:plex-utills chris$ python3 setup_helper.py 
Traceback (most recent call last):
  File "setup_helper.py", line 16, in <module>
    server = config_object["PLEXSERVER"]
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'PLEXSERVER'
`
is that my config set up wrong ?

**Comment by manuelbraeuer** [comment]
you need to change the paths in the py file. i am using windows, so i've to escape the path by double \ . try to write down the path to your plex-utills folder

`config_object = ConfigParser()`
`config_object.read("c:\\path\\plex-utils\\config\\config.ini")`
`server = config_object["PLEXSERVER"]`
`baseurl = (server["PLEX_URL"])`
`token = (server["TOKEN"])`
`plexlibrary = (server["FILMSLIBRARY"])`
`ppath = (server["PLEXPATH"])`
`mpath = (server["MOUNTEDPATH"])`
`pbak = str.lower((server["POSTER_BU"]))`
`HDR_BANNER = str.lower((server["HDR_BANNER"]))`
`plex = PlexServer(baseurl, token)`
`films = plex.library.section(plexlibrary)`
`mini_4k = str.lower((server["mini_4k"]))`
`banner_4k = Image.open("c:\\path\\plex-utils\\img\\4K-Template.png")`
`mini_4k_banner = Image.open("c:\\path\\plex-utils\\img\\4K-mini-Template.png")`
`banner_hdr = Image.open("c:\\path\\plex-utils\\img\\hdr-poster.png")`
`chk_banner = Image.open("c:\\path\\plex-utils\\img\\chk-4k.png")`
`chk_mini_banner = Image.open("c:\\path\\plex-utils\\img\\chk-mini-4k.png")`
`chk_hdr = Image.open("c:\\path\\plex-utils\\img\\chk_hdr.png")`

and also the config.ini

`[PLEXSERVER]`
`PLEX_URL = http://127.0.0.1:32400`
`TOKEN = your-token-here`
`FILMSLIBRARY = Movies`
`#Use the setup helper if you don't know what to use here.`
`PLEXPATH = c:\\path\\pms\\Plex Media Server\\Media`
`# no trailing slash.`
`MOUNTEDPATH = c:\\path\\movies`

**Comment by jkirkcaldy** [comment]
For Windows you can also use forward slashes which I found solved a few escaping issues in my testing. 
So `c:\\path\\pms\\Plex Media Server\\Media` can be written as `c:/path/pms/Plex Media Server/Media`

**Comment by Silentbob101** [comment]
Thanks for the help! I have this working now gonna carry on tinkering with this!
