### ISSUE TITLE
hide-4k.py not adding "Untranscodable" tag

### ISSUE THREAD

**Issue by Turbo123T3** [jkirkcaldy/plex-utills#23]
Hello, so i've gotten,

4k_hdr_poster.py
Pixar_collection..py
disney_collection.py
restore_posters.py

to all run just fine. It generates the thumbnails perfectly, it adds movies to the collections perfectly. However when I run hide-4k.py it doesn't give an error or any message and acts as if it ran. I can manually add the "Untranscodable" tag to to movies and accounts, which works just fine and they even come back when I manually optimize a video to 1080p.

Also is there a way to change the "transcode" setting to a custom transcode of 720p?

**Comment by jkirkcaldy** [comment]
I'm working on adding a couple of new features and working out a couple of bugs, I'll add some feedback to the hide-4k script. 

I also need to update/write more documentation on how to get everything working.

**Comment by curious44** [comment]
This is also not working for me.  I am running the latest version.  I don't see the tag being added.

**Comment by jkirkcaldy** [comment]
Fixed in the next commit.
