### ISSUE TITLE
getting this error message when running Im using the CA on unraid and the container is set to bridge mode

### ISSUE THREAD

**Issue by bquedens** [jkirkcaldy/plex-utills#24]
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
conn = connection.create_connection(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.9/http/client.py", line 1257, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1303, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1252, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1012, in _send_output
self.send(msg)
File "/usr/local/lib/python3.9/http/client.py", line 952, in send
self.connect()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
conn = self._new_conn()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x14fb44fbf640>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='your_plex_ip_address', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14fb44fbf640>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/app/./4k_hdr_poster.py", line 31, in <module>
plex = PlexServer(baseurl, token)
File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 116, in __init__
data = self.query(self.key, timeout=self._timeout)
File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 659, in query
response = method(url, headers=headers, timeout=timeout, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='your_plex_ip_address', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14fb44fbf640>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by Turbo123T3** [comment]
This was one of the errors I was having as well the other night, I believe your issue is the "PLEX_URL" I had to make mine my public ip not my servers internal ip. I also added the plex port at the end so http://PUBLICIP:PORT

**Comment by jsbear** [comment]
I'm having issues as well, can you share an example for your config file?  I found the instructions to be very confusing.

**Comment by Turbo123T3** [comment]
```
[PLEXSERVER]
PLEX_URL = http://EXTERNALIP:32400
TOKEN = <THETOKEN>
FILMSLIBRARY = Movies
#Use the setup helper if you don't know what to use here.
PLEXPATH = /media/Movies
# no trailing slash.
MOUNTEDPATH = /films
```

& remember /films is /films because if you use the Unraid Docker he has it set so the "Plex Library" from inside the docker is /films

https://drive.google.com/open?id=1jpBA-TwAYvWNk9v5u-Q2tc-jgOg2X8bu

That has to be linked to the MOVIES directory you're using for /films to work. Not just your Plex folder.

**Comment by jsbear** [comment]
Appreciate the help, I was close.   A few tweaks and I'm up and running.

Thanks again.

**Comment by Laseracid** [comment]
> ```
> [PLEXSERVER]
> PLEX_URL = http://EXTERNALIP:32400
> TOKEN = <THETOKEN>
> FILMSLIBRARY = Movies
> #Use the setup helper if you don't know what to use here.
> PLEXPATH = /media/Movies
> # no trailing slash.
> MOUNTEDPATH = /films
> ```
> 
> & remember /films is /films because if you use the Unraid Docker he has it set so the "Plex Library" from inside the docker is /films
> 
> https://drive.google.com/open?id=1jpBA-TwAYvWNk9v5u-Q2tc-jgOg2X8bu
> 
> That has to be linked to the MOVIES directory you're using for /films to work. Not just your Plex folder.

I'm also trying to set this up on unraid where do I add this?  Are they all Values like your image?

**Comment by Turbo123T3** [comment]
Okay so the text part is in the configuration file on the server itself in your app data under where you installed the actual docker in the image.

The image is the docker itself so there is the movies folder when you edit the docker in the ubraid webgui as well as the install location for thr docker. Make sure the movies folder where you edit your docker is the actual movies folder that you're going to be generating the 4k images in.

And the configuration file can be edited on the server itself like you would for any other docker, in the appdata folder.

**Comment by bquedens** [comment]
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
> conn = connection.create_connection(
> File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
> for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
> File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
> for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
> httplib_response = self._make_request(
> File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
> conn.request(method, url, **httplib_request_kw)
> File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
> super(HTTPConnection, self).request(method, url, body=body, headers=headers)
> File "/usr/local/lib/python3.9/http/client.py", line 1257, in request
> self._send_request(method, url, body, headers, encode_chunked)
> File "/usr/local/lib/python3.9/http/client.py", line 1303, in _send_request
> self.endheaders(body, encode_chunked=encode_chunked)
> File "/usr/local/lib/python3.9/http/client.py", line 1252, in endheaders
> self._send_output(message_body, encode_chunked=encode_chunked)
> File "/usr/local/lib/python3.9/http/client.py", line 1012, in _send_output
> self.send(msg)
> File "/usr/local/lib/python3.9/http/client.py", line 952, in send
> self.connect()
> File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
> conn = self._new_conn()
> File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
> raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x14fb44fbf640>: Failed to establish a new connection: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
> resp = conn.urlopen(
> File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
> retries = retries.increment(
> File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> 
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='your_plex_ip_address', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14fb44fbf640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/app/./4k_hdr_poster.py", line 31, in
> plex = PlexServer(baseurl, token)
> File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 116, in **init**
> data = self.query(self.key, timeout=self._timeout)
> File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 659, in query
> response = method(url, headers=headers, timeout=timeout, **kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
> return self.request('GET', url, **kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
> resp = self.send(prep, **send_kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
> r = adapter.send(request, **kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='your_plex_ip_address', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14fb44fbf640>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Solved not sure how to close

**Comment by jsbear** [comment]
Mine was working great, until I updated the docker.  After updating, I updated the new config.ini associated with the new version.  Now I can't start the docker in Unraid.   I get the following error.

/config/config.ini already exists

**Comment by jkirkcaldy** [comment]
The config exists message is given before anything else. All that means is that the config file exists so it won’t try to copy the config file from the docker and overwrite it.   
  

  
Does anything else happen, any other messages?   
  
  
  
    
  

  
  
>

**Comment by jsbear** [comment]
No other messages at all, docker will not start.  I will double check config again.

**Comment by bquedens** [comment]
> No other messages at all, docker will not start. I will double check config again.

I’m having the same issues since updating the docker on unraid is there a way you can rollback the update
