### ISSUE TITLE
KeyError: 'PLEXSERVER'

### ISSUE THREAD

**Issue by timmehtimtims** [jkirkcaldy/plex-utills#26]
I'm getting an odd error when using the latest version of this script and I'm slightly confused by the config.ini. I can't remember how I had it setup and working before so would appreciate some help. I'm running it on a headless linux server running Ubuntu 18.04. I'm getting the following error running `python3 4k_hdr_poster.py`:

```Traceback (most recent call last):
  File "4k_hdr_poster.py", line 23, in <module>
    server = config_object["PLEXSERVER"]
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'PLEXSERVER' 
```
My config is:
```[PLEXSERVER]
PLEX_URL = http://EXTERNAL-IP:32400 - I have tried this using http://plex:32400
TOKEN = TOKEN
FILMSLIBRARY = 4K Movies
#Use the setup helper if you don't know what to use here. - the setup helper doesn't work either
PLEXPATH = /mnt/unionfs/4K/movies - location of movies directory. Have tried using /opt/appdata/plex but this didn't work either 
# no trailing slash.
MOUNTEDPATH = /mnt/unionfs/4K/movies
```

Any advice appreciated.

**Comment by jkirkcaldy** [comment]
This usually means that the script can't see the config file. 

Take out the initial / in the line `config_object.read("/config/config.ini")` and that should work. 

This fix is coming in an update soon.

**Comment by timmehtimtims** [comment]
Nice, that did the trick.
