### ISSUE TITLE
Mine was working great, until I updated the docker.  After updating, I updated the new config.ini associated with the new version.  Now I can't start the docker in Unraid.   I get the following error.

### ISSUE THREAD

**Issue by bquedens** [jkirkcaldy/plex-utills#29]
Mine was working great, until I updated the docker.  After updating, I updated the new config.ini associated with the new version.  Now I can't start the docker in Unraid.   I get the following error.

/config/config.ini already exists

_Originally posted by @jsbear in https://github.com/jkirkcaldy/plex-utills/issues/24#issuecomment-894600288_

**Comment by bquedens** [comment]
Having the same issue with the docker in unraid as @jsbear is having

**Comment by Magikarplvl4** [comment]
I have the same issue, I updated the docker container on my unraid server, no error has been thrown in the logs, the only thing that is reported is: "Exited (0): Less than a second ago".
Not sure what i can do to troubleshoot this one, can you give me some advice on this? 

@bquedens can you make your title a little shorter :/

**Comment by Magikarplvl4** [comment]
@bquedens can you post your config.ini?

**Comment by ados8** [comment]
Please rename title :)
Backup your config and delete it, then have the docker create it as it contains new code.
Then copy your settings over to the new config keeping the new code.

**Comment by bquedens** [comment]
So i ended up taking the new code from git to replace all the old code in the config.ini it works now
