### ISSUE TITLE
Updated Poster/Banner is not used

### ISSUE THREAD

**Issue by Vap0rz** [jkirkcaldy/plex-utills#31]
When running the docker it looks as if everything is working OK (config.ini set up correctly) but the poster selected for a movie doesn't get updated.  If I go into plex and click edit on the poster (any 4k movie), it does show there is a poster with the banner on top but it is not selected automatically. If I select it manually it works fine after clearing browser cache.

I've run the check and setup scripts with a 'pass' but I'm not really sure where to even start looking to fix the problem. This is running on an Unraid server with Movies being the root, each movie is in it's own folder if that makes a difference.

Is there anything I can check?
Thanks

**Comment by curious44** [comment]
What does your Config look like?

**Comment by Vap0rz** [comment]
Thanks for checking on this-

Docker settings:
Plex Library  /mnt/user/Media/Movies/G-P/
Config file /mnt/disks/ssd/appdata/plex-utills/

Here is the config:
[PLEXSERVER]
PLEX_URL = removed
TOKEN = removed
# This should match the library title seen in Plex
FILMSLIBRARY = Movies
3D_Library = 3D-Films
#Use the setup helper if you don't know what to use here.
PLEXPATH = /media

# If using Docker, leave this as /films. No trailing slash.
MOUNTEDPATH = /films

[SCHEDULES]
#enter the time of day you want the script to run
4k_poster_schedule = 23:00
3d_poster_schedule = 22:45
disney_schedule = 22:00
pixar_schedule = 22:10
hide_poster_schedule = 01:00

[DOWNLOADERS]
#Coming Soon
sonarrurl = "https://sonarrurl"
sonarrapi = "sonarapi"
radarrurl = "https://radarurl"
radarrapi = "radarrapi"

[OPTIONS]
# Enter either True or False only to turn on/off the features you wish to use.
#Create a backup of your posters before adding banners. This is global for 4k/HDR or 3D films
POSTER_BU = false

4k_hdr_posters = true
mini_4k = false
HDR_BANNER = TRUE

3D_posters = false
mini_3D = false

Disney = True
Pixar = true
hide_4k = false

#Set this to true, if you would like your Plex Server to create an optimised HD version of your 4K films. This is not reccomended on low powered hardware
transcode = false


#Use ffmpeg to check for corrupted files. It will check files added in however many days you set below.
CHECK_FILES = true
#Set the number of days you want to go back and check, the longer you go back the longer the checks will take.
CHECK_FILES_HISTORY = 20



From inside the docker /films does show its mounted to my media share:
# ls -lah /films
drwxrwxrwx 1 1000  1000  215 Sep  3 03:32  .
drwxr-xr-x 1 root root    44 Oct  8 01:59  ..
drwxrwxrwx 1 1000  1000   32 May 26  2013  .@__thumb
drwxrwxrwx 1 1000  1000 4.0K Jun 22  2017 'removed'
drwxrwxrwx 1 1000  1000  288 Jun 22  2017 'removed2'
drwxrwxrwx 1 1000  1000 4.0K Jul  6  2020 'blah blah'

I'm leaning more towards a plex thing but if nobody else is having issues it must be something I've done?
Any help would be appreciated !

**Comment by curious44** [comment]
Update PLEXPATH to "/mnt/user/Media/Movies/G-P" and try again.

**Comment by Vap0rz** [comment]
Thanks again,
The issue was that the movies are broken up in different folder (A-F) (G-M) etc so I was messing with the path names and set it improperly. My apologies! <closed>
