### ISSUE TITLE
Atmos / DTS:X support

### ISSUE THREAD

**Issue by KrunchMuffin** [jkirkcaldy/plex-utills#34]
Would it be possible to add support for these object sound formats? Plex won't add it ever.

**Comment by jkirkcaldy** [comment]
As the script uses the plex api to find 4k files, there is currently no way of seeing whether a file has atmos/dts:x soundtracks through the api. 

I can look into whether it is possible to add this outside of plex.

**Comment by KrunchMuffin** [comment]
As a start, you should be able to identify 7.1 since Plex has that info.

**Comment by jkirkcaldy** [comment]
Testing this now. Detection is working and the posters look like this:

![poster](https://user-images.githubusercontent.com/26098592/143296052-111b0897-57c6-4aa9-a469-d9f18ee3481c.png
![1637778724](https://user-images.githubusercontent.com/26098592/143296690-c5a3c845-8fa5-4944-845a-5153fac6d57b.png)
)

**Comment by KrunchMuffin** [comment]
sweet, that works

**Comment by KrunchMuffin** [comment]
Just a small typo I noticed since ur in the code.

> Enabled scrpts are shown below:

scripts missing i

**Comment by KnifeFed** [comment]
Another approach to this could be to combine the HDR/DV banner with the Atmos/DTS:X banner, i.e. having the audio logo next to/underneath the HDR/DV logo. Having three different banners in three different places could potentially look messy. Even now, with two banners, I've encountered some instances where "vital" parts of the poster are partially covered (mainly by the HDR banner).

Furthermore, I think it would be really nice to have a banner with _only_ HDR/DV (+ audio). In my case, for example, I don't have any media that's HDR/DV and _not_ 4K – making a dedicated 4K banner redundant.
The ideal for me would be to have a single banner that shows one of:

- `4K` for non-HDR 4K with non-object-based audio.
- `4K Atmos/DTS:X` for non-HDR 4K with Atmos/DTS:X.
- `HDR/DV` for HDR/DV with non-object-based audio.
- `HDR/DV Atmos/DTS:X` for HDR/DV with Atmos/DTS:X.

Just my ¢2 :)

**Comment by KrunchMuffin** [comment]
That won't work for me. I don't have 4k nor do I have HDR/DV.

**Comment by KnifeFed** [comment]
Ok, so just a single banner with `Atmos/DTS:X` then.

**Comment by KrunchMuffin** [comment]
There can only be one object audio type per movie. AFAIK.
But I want to distinguish between them both. I don't want one banner that shows both.

**Comment by KnifeFed** [comment]
Yeah, every time I wrote "HDR/DV" and "Atmos/DTS:X" I meant _either-or_, i.e. only one of the logos.

**Comment by ApfelBirneKreis** [comment]
Quick question how do you guys deal with your DV content? Uncompressed?

**Comment by jkirkcaldy** [comment]
Had a little re-design. Adding them to the bottom of the HDR banners. It needs to be a design that can be used in conjunction with all the existing banners. I think this newer design works well with this. 
![atmos example](https://user-images.githubusercontent.com/26098592/143590749-49ab26e3-486a-44b6-adfb-ac6f4630ef7d.png)
![dtsx example](https://user-images.githubusercontent.com/26098592/143590754-bf4fd1a4-08a8-494f-949f-023f34beb1bf.png)

**Comment by KnifeFed** [comment]
That is actually the [old](https://logos.fandom.com/wiki/DTS_X) DTS:X logo. [Here](https://static.wikia.nocookie.net/logopedia/images/e/e5/DTS_X_2020_%28Print%29.svg/revision/latest?format=original) is the new one, in monochrome.
