### ISSUE TITLE
Feature Request: Add support for Dolby Vision

### ISSUE THREAD

**Issue by zerocool79** [jkirkcaldy/plex-utills#37]
Can we have have different banners for regular HDR and Dolby Vision content?

**Comment by jkirkcaldy** [comment]
Potentially, I need to figure out if there is a way to get that information from the api. As currently the script just checks for HDR content regardless of the format.

**Comment by jgog** [comment]
can you check for the file name containing `Dolby Vision` to start with?

**Comment by jkirkcaldy** [comment]
This is coming in the next release. 
Different HDR banners for Dolby Vision, HDR10+ and HDR10

**Comment by jkirkcaldy** [comment]
Added.
