### ISSUE TITLE
Support for different movie directories for UHD and HD

### ISSUE THREAD

**Issue by alexandzors** [jkirkcaldy/plex-utills#38]
Saw this on Reddit and would like to use this now that I am starting to acquire UHD content. However it looks like its limited to having both the HD and UHD copies in the same directory. Would it be possible to support having UHD and HD in separate directories?

I have them joined in Plex under the same movies library but the local dir is `/movies` and `/movies_4k` due to having two different Radarr instances managing them.

I saw #14 so maybe this is related?

**Comment by jkirkcaldy** [comment]
This is exactly how I have my media saved. 

You should use the root plex media directory not the movies directory. 

So if your movies are saved under `/mnt/user/Plex/movies` and 4k under `/mnt/user/Plex/movies-4k` make sure that you use the mount point `/mnt/user/Plex` in the config. And making sure that the `PLEXPATH` uses the root directory too

**Comment by alexandzors** [comment]
Finally got back around to messing with this stuff. So I just mount `/media/plex` to `/films` in the container so the container can then see both `/movies` and `/movies_4k`?

And I assume this script doesn't support Windows for the PLEXPATH? atm Plex is mounting the movies directory under `H:\Movies` and H:\Movies_4K`

Basically my setup is:
Windows 10 Workstation running Plex + Hyper-V
Hyper-V VM running Ubuntu Server with Docker (which is where plex utils is running)

Plex media is in a storage spaces array on windows and shared with the Linux VM over SMB.

**Comment by jkirkcaldy** [comment]
Windows is supported.   
  

  
  
 Your PLEXPATH would be `H:/` I believe.   
  
  
  

  
  
>
