### ISSUE TITLE
Error: cannot see media libraries in helper script

### ISSUE THREAD

**Issue by g0d-m0nky** [jkirkcaldy/plex-utills#41]
I am running docker. I am sure the problem is with my pathing, but I can't figure out what to put.

My setup is as follows:

- my films library is called 'Films'
- my 4k movies folder as plex sees it in docker is `/storage/mergerfs/medialibrary/movies_4k`

My config is as follows:
```
# This should match the library title seen in Plex
FILMSLIBRARY = Films
#Use the setup helper if you don't know what to use here.
PLEXPATH = /storage                                

# If using Docker, leave this as /films. No trailing slash.
MOUNTEDPATH = /films
```

I'd really appreciate suggestions on what I have wrong.

**Comment by jkirkcaldy** [comment]
So it's the directory as the Plex docker container sees it. 

If you pull the latest version, the logs should automatically tell you what the Plex path should be. 

For reference, the Plex Inc docker container the plexpath should be /media. For the binhex container it should be /data

I hope that makes sense.

**Comment by g0d-m0nky** [comment]
[This was the solution for me](https://github.com/jkirkcaldy/plex-utills/issues/22#issuecomment-907753365)
