### ISSUE TITLE
Add documentation for docker usage

### ISSUE THREAD

**Issue by Pxmme** [jkirkcaldy/plex-utills#49]
Hi,

First of all, thanks for creating this script. I am looking forward to using it. I'm well-versed into Unix but not at all into Docker.

I run my Plex server on Ubuntu and my medias are on an NFS share hosted in Unraid.

As of today, here is the only "documentation" in order to make this work with Docker:

> For a docker on any other system, run

> docker run -d -p 80:80 -v <your/plex/media>:/films -v <mount/your/logs>:/logs -v <your/config>:/config -e TZ=Europe/london -e PUID=1000 -e PGUI=1000 jkirkcaldy/plex-utills

> From there go to http://<your_ip> to continue

I setup another VM on the same local network as the rest, installed docker, then started it via this command:

> docker run -d -p 80:80 -v /mnt/medias:/films -v /var/log:/logs -e TZ=Europe/london -e PUID=1000 -e PGUI=1000 jkirkcaldy/plex-utills

I then added my Plex's URL and "api key" on the web UI. Finally, I manually started the 4K banner script, and checked the logs: I got an error.

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'run_posters4k' did not return a valid response. The function either returned None or ended without a return statement.
```

What am I missing here? Generally speaking, would it be possible to have something a tad more explanatory when it comes to using this on Docker?

Thanks again for your hard work.

**Comment by jkirkcaldy** [comment]
This error has been sorted with version 21.11 on docker hub
