### ISSUE TITLE
Feature Request: More then 1 Script run Schedule.

### ISSUE THREAD

**Issue by fscorrupt** [jkirkcaldy/plex-utills#53]
I would love to run the script for 4k banner lets say every hour, or twice a day or on different times a day. Would it be possible to add such a feature. Once a day is in most cases not enough and i manually trigger it.

**Comment by notoriousjere** [comment]
Yeah I'd say honestly this could be solved by allowing us to enter cron syntax. Any learning curve would be solved by embedding a link to https://crontab.guru/ on the config page, but you'd figure if someone can set up docker they can learn cron syntax.
 The python croniter package has a function called croniter.is_valid that takes the raw user input string for validation.

**Comment by jkirkcaldy** [comment]
It shouldn't be too difficult to allow either format. I'll have a look into it over the next couple of days

**Comment by jkirkcaldy** [comment]
You can now use either time formatting (HH:MM) or a cron format for the schedules in the dev container. I'm doing some tests but this will be pushed out to the :latest soon

You  can also use webhooks from Tautulli and Radarr to run the script on the film that has just been added. as explained here. (again, only in the dev container at the moment.  #90
