### ISSUE TITLE
Execution Error when updating

### ISSUE THREAD

**Issue by wgstarks** [jkirkcaldy/plex-utills#60]
Attempted to update the docker on unraid but I get an execution error when I try to start the docker. Logs are blank.
Run Command-
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='plex-utills' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'TZ'='America/New_York' -e 'PUID'='999' -e 'PGID'='1000' -p '5000:5000/tcp' -p '80:80/tcp' -v '/mnt/user/Media/XBMC/Torrents/':'/films':'rw' -v '/mnt/cache/appdata/plex-utills':'/config':'rw' -v '/mnt/user/appdata/plex-utills/logs':'/logs':'rw' 'jkirkcaldy/plex-utills' 
ec566bd7ef1478ee231b2b9e6c3742718fa0149599cf5f190674953f7d5cb1ce
`

I tried deleting/reinstalling and I get this error-
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='plex-utills' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'TZ'='America/New_York' -e 'PUID'='999' -e 'PGID'='1000' -p '5000:5000/tcp' -p '80:80/tcp' -v '/mnt/user/Media/XBMC/Torrents/':'/films':'rw' -v '/mnt/cache/appdata/plex-utills':'/config':'rw' -v '/mnt/user/appdata/plex-utills/logs':'/logs':'rw' 'jkirkcaldy/plex-utills' 
27d614ab6bf0cc364c981bdf0ef663d5ee093104ff63cb1282d361bc948652b2 docker: Error response from daemon: driver failed programming external connectivity on endpoint plex-utills (f42fc3b826318447dba6be83b68ea804c0d85510e2d2c80ce807a200122d3483): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use.`

**Comment by bquedens** [comment]
Same issues here when I delete port 80 it works but no web ui would love to get the web ui to work I’m using unraid

**Comment by wgstarks** [comment]
> Same issues here when I delete port 80 it works but no web ui would love to get the web ui to work I’m using unraid

That's the solution I believe. Somehow after updating I have two webui ports. Both are configured the same except for the port number. One is port 80 and the other is port 5000. After deleting the entry for port 80 everything works and I can access the webui on port 5000 as previously. Not sure where the extra port entry came from though and why I didn't get an error that the port was already in use???

**Comment by jkirkcaldy** [comment]
Looks like something is already using port 80 on your server.   
  

  
Try changing it to a different port like -p 8080:80   
  
  
  
    
  

  
  
>

**Comment by wgstarks** [comment]
I already had it set to 5000 before updating. Not sure why the update added a second port for the webUI??? Does the ui require 2 ports?

**Comment by jkirkcaldy** [comment]
you only need to use port 80 from the docker container. Port 5000 has been left exposed for troubleshooting and of those that had it already set up.

**Comment by wgstarks** [comment]
Thanks. I suspected that but wanted to confirm.
