### ISSUE TITLE
Feature Request: Versioning

### ISSUE THREAD

**Issue by wgstarks** [jkirkcaldy/plex-utills#61]
I'm not a docker guru so no idea how hard this would be to implement but tagged version support would allow the ability to install any previous version based on tag and easily overcome any new bugs until they are resolved. Maybe I'm just missing it but there don't seem to be any version numbers for updates.

**Comment by curious44** [comment]
Docker hub has the version under their tags tab. 

[Docker Hub](https://hub.docker.com/r/jkirkcaldy/plex-utills/tags?page=1&ordering=last_updated) 

Once you have tag number just add after the repository name.   Ex. jkirkcaldy/plex-utills:21.9

**Comment by wgstarks** [comment]
DUH
I don't know why I didn't check on docker hub before posting this.
