### ISSUE TITLE
Paths not Matching Up

### ISSUE THREAD

**Issue by Bnittym5** [jkirkcaldy/plex-utills#63]
I have "/Movies" as my Plex Path.

But it can't find them because it's looking under "/films" even after changing it in the config and database manually. What am I missing here?

**Comment by KnifeFed** [comment]
Same here. I mapped the `/films` container path to my `/mnt/user/movies/lib` host path. In the log, I'm getting:

`[Errno 2] No such file or directory: '/films/movies/lib/10 Cloverfield Lane (2016)/poster_bak.png'`

Also, I keep separate shares for movies/TV etc. (like many others do) so I can't really do as the installation instructions say: "You should pass though the _root directory_ containing all your plex media, not just the films/movies directories."

**Comment by wgstarks** [comment]
> I mapped the `/films` container path to my `/mnt/user/movies/lib` host path.


Just to verify, this is the path to the actual video files? Remember it’s case sensitive so movies isn’t the same as Movies (just an idea).

**Comment by wgstarks** [comment]
> Also, I keep separate shares for movies/TV etc. (like many others do) so I can't really do as the installation instructions say: "You should pass though the _root directory_ containing all your plex media, not just the films/movies directories."

I haven’t tested this but you should be able to run two instances of the docker. One for movies and one for TV.

**Comment by KnifeFed** [comment]
> > I mapped the `/films` container path to my `/mnt/user/movies/lib` host path.
> 
> Just to verify, this is the path to the actual video files? Remember it’s case sensitive so movies isn’t the same as Movies (just an idea).

It's the path to where each movie folder is contained, i.e. "10 Cloverfield Lane (2016)". And yeah, it's all lowercase.

**Comment by KnifeFed** [comment]
> > Also, I keep separate shares for movies/TV etc. (like many others do) so I can't really do as the installation instructions say: "You should pass though the _root directory_ containing all your plex media, not just the films/movies directories."
> 
> I haven’t tested this but you should be able to run two instances of the docker. One for movies and one for TV.

Yeah, I could do that. I just need to get it working first.

**Comment by wgstarks** [comment]
> I have "/Movies" as my Plex Path.
> 
> But it can't find them because it's looking under "/films" even after changing it in the config and database manually. What am I missing here?

Don’t change the host path. Just set a container path to point to your video files.

**Comment by wgstarks** [comment]
> > I haven’t tested this but you should be able to run two instances of the docker. One for movies and one for TV.
> 
> Yeah, I could do that. I just need to get it working first.

Try adding a trailing slash `/mnt/user/movies/lib/`
That’s how mine is formatted.

**Comment by KnifeFed** [comment]
> Try adding a trailing slash `/mnt/user/movies/lib/` That’s how mine is formatted.

Yeah, that is actually how I have it. What is your host path?

**Comment by wgstarks** [comment]
> > Try adding a trailing slash `/mnt/user/movies/lib/` That’s how mine is formatted.
> 
> Yeah, that is actually how I have it. What is your host path?

![BrunnhildeUpdateContainer](https://user-images.githubusercontent.com/5657833/142916235-c94bdfea-d014-44f4-af05-1cc977a1582b.png)

**Comment by KnifeFed** [comment]
Weird. And you do have "Enable Poster Backups" set to "True"?

**Comment by wgstarks** [comment]
The only other thing I can think of would be to restart the docker container.

**Comment by wgstarks** [comment]
> Weird. And you do have "Enable Poster Backups" set to "True"?

Yes

**Comment by KnifeFed** [comment]
Yeah, I've restarted it and reinstalled it. Same issue. Thanks for your help though.

**Comment by Bnittym5** [comment]
<img width="981" alt="Screen Shot 2021-11-22 at 3 59 34 PM" src="https://user-images.githubusercontent.com/36997894/142941411-51224abe-e492-4f14-aabb-92efbb292012.png">

No matter what I do I can't change the Plex Library from being pointed at /films

<img width="252" alt="Screen Shot 2021-11-22 at 4 07 36 PM" src="https://user-images.githubusercontent.com/36997894/142942295-6d95696d-9909-4dac-9a6e-7d3423090f56.png">
s

**Comment by Bnittym5** [comment]
> Same here. I mapped the `/films` container path to my `/mnt/user/movies/lib` host path. In the log, I'm getting:
> 
> `[Errno 2] No such file or directory: '/films/movies/lib/10 Cloverfield Lane (2016)/poster_bak.png'`
> 
> Also, I keep separate shares for movies/TV etc. (like many others do) so I can't really do as the installation instructions say: "You should pass though the _root directory_ containing all your plex media, not just the films/movies directories."

Try a fresh install, point it directly at your "/Movies" folder when you set up the container. It worked for me. So for no I have to do a separate install with it pointing at TV Shows for it to work.

<img width="665" alt="Screen Shot 2021-11-22 at 4 34 40 PM" src="https://user-images.githubusercontent.com/36997894/142945118-12f2984c-7f79-48d1-b651-62ec51ffe600.png">

**Comment by wgstarks** [comment]
> No matter what I do I can't change the Plex Library from being pointed at /films
> 

The container path is always /films. You set the host path to point to the location of your media. For example, on my server /films=/mnt/user/Media/Movies. Where the logs show /films that’s actually whatever you have set for the host path.

**Comment by wgstarks** [comment]
> Yeah, I've restarted it and reinstalled it. Same issue. Thanks for your help though.

I deleted my docker and appdata. Did a fresh install and everything is still working great. You might try the same. When you set the path for Plex Library try using the builtin file browser in unRAID.

**Comment by KnifeFed** [comment]
I had to set my host path to `/mnt/user/` for it to work. I noticed this in the application log:

`SYS - Updater: Your plexpath has been changed to /data`.

My Plex container has `/data` mapped to `/mnt/user/`.

So `/films` can not just simply be pointed to the location of your media files, it has to match the Plex container path as well? That could use some clarification in the installation instructions.

**Comment by wgstarks** [comment]
@KnifeFed 
Glad you got it.

**Comment by jkirkcaldy** [comment]
> I had to set my host path to `/mnt/user/` for it to work. I noticed this in the application log:
> 
> `SYS - Updater: Your plexpath has been changed to /data`.
> 
> My Plex container has `/data` mapped to `/mnt/user/`.
> 
> So `/films` can not just simply be pointed to the location of your media files, it has to match the Plex container path as well? That could use some clarification in the installation instructions.

/films is used becaus the app originally only supported films. But in reality it doesn't matter what is used in the docker container as the script will convert your Plex filepath to a path the Plex-utills container can see. 

you should be using whatever mountpoint you give to plex in the plex-utills container. Then the container will change `/data` or `/media` to `/films` so it knows where your files are. 

I'll add this into the documentation so it's a bit easier to understand.

This is my first real dive into coding/releasing an app for public consumption and the amount of variables there are to account for the way people organise their data is an eye opener.

**Comment by KnifeFed** [comment]
@jkirkcaldy Thanks for the clarification, I appreciate it! What a fun project to get your feet wet. You're doing a great job :)

**Comment by KnifeFed** [comment]
@Bnittym5 You have this working too now right? So this issue can be closed.
