### ISSUE TITLE
[FR] Move original poster down, instead of adding banner on top.

### ISSUE THREAD

**Issue by pairofcrocs** [jkirkcaldy/plex-utills#67]
I just started using this awesome script, but I've noticed something right away that I feel could be improved upon.

I'm using the regular 4k banner (the one that takes up the entire top part of the poster) and it seems to work about 70% of the time. The other 30% is when there's text on the top of the poster, and it will cover that up.

I think a solution could be to move the original poster, and the put the banner in place of it.

Yes, sometimes there's text on the bottom, but it seems like more of them are on the top vs the later.

**Comment by JStrongy** [comment]
+1 on this!

Current functionality is working great and from my POV, this is literally the only niggle I have.

Keep up the good work!

**Comment by jkirkcaldy** [comment]
Just testing this but I think moving the poster down is going to have a similar negative effect on the bottom of the poster. 

Adding the banner to the top of the poster does this inside plex:

![image](https://user-images.githubusercontent.com/26098592/150109011-7fd76914-385c-4bdc-a639-307280e155a5.png)


Wheras moving the poster down looks fine for that poster, when the title is at the bottom, it clips the title looking like this:

![image](https://user-images.githubusercontent.com/26098592/150108928-27bf095a-d680-4b47-a5d4-cda55cf6e431.png)

As there isn't an easy way to check whether the title is at the top or the bottom and there is always going to be a compramise somewhere, I think for now I'm going to leave it as is.
