### ISSUE TITLE
incorrect movie poster

### ISSUE THREAD

**Issue by cdthomo** [jkirkcaldy/plex-utills#69]
Very specific issue, not sure how to debug.

Plex utils is running on my unraid server and adds the 4K and HDR banners to my posters in Plex.

For some reason the poster for the film Nobody (2021) gets replaced with the poster for Dune (2021) each time. No other movies are effected.

Advice welcomed.

**Comment by curious44** [comment]
I also have nobody 4k.  I do get the correct poster with 4k banner.  Could there be something wrong with Metadata for the file?

**Comment by cdthomo** [comment]
thanks for the info.

I also have plex-meta-manager running immediately before plex utils so this may be the issue, I'll investigate this as the source of the problem too. I'll stop PMM from running tomorrow and see if it still happens.

**Comment by jkirkcaldy** [comment]
I have noticed that the script sometimes replaces posters with the incorrect poster and I am testing a solution to this as we speak.

**Comment by jkirkcaldy** [comment]
Fixed this in the next release. Temp posters now use the film name and check that they match before uploading.
