### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by KrunchMuffin** [jkirkcaldy/plex-utills#70]
Even though I set my library to Movies in config, it is still trying to go to Films.
v21.12

![image](https://user-images.githubusercontent.com/1037197/145057817-6e966ce9-5a4b-4b00-9a1c-703779b6f506.png)

> 2021-12-07 10:24:17,634 - plex-utills - 4k Posters: 4k HDR poster script starting now.
> 2021-12-07 10:24:20,091 - plex-utills - Scanning Rat Race
> Exception in thread Thread-2:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
> self.run()
> File "/usr/local/lib/python3.9/threading.py", line 910, in run
> self._target(*self._args, **self._kwargs)
> File "/app/app/scripts.py", line 594, in posters4k
> get_audio()
> File "/app/app/scripts.py", line 119, in get_audio
> m = MediaInfo.parse(file, output='JSON')
> File "/usr/local/lib/python3.9/site-packages/pymediainfo/__init__.py", line 494, in parse
> raise FileNotFoundError(filename)
> FileNotFoundError: /films/Rat Race (2001)/Rat Race (2001).mp4

**Comment by KrunchMuffin** [comment]
FYI, I even tried restarting container on unraid.

> 2021-12-07 10:29:26,096 - SYS - 4K/HDR Posters schedule created for 00:00
> 2021-12-07 10:29:26,096 - SYS - Auto Collections schedule created for 00:00
> 2021-12-07 10:29:28,816 - SYS - Updater: Your plexpath has been changed to /movies
> 2021-12-07 10:29:29,040 - SYS - Updater: Your plexpath has been changed to /movies
> 2021-12-07 10:29:29,042 - SYS - Updater: Your plexpath has been changed to /movies
> 2021-12-07 10:29:29,044 - SYS - Updater: Your plexpath has been changed to /movies
> 2021-12-07 10:29:29,040 - SYS - Updater: Your plexpath has been changed to /movies
> 2021-12-07 10:29:29,042 - SYS - Updater: Your plexpath has been changed to /movies
> 2021-12-07 10:29:29,044 - SYS - Updater: Your plexpath has been changed to /movies
> 2021-12-07 10:29:36,974 - plex-utills - 4k Posters: 4k HDR poster script starting now.
> 2021-12-07 10:29:39,536 - plex-utills - Scanning Rat Race
> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
> self.run()
> File "/usr/local/lib/python3.9/threading.py", line 910, in run
> self._target(*self._args, **self._kwargs)
> File "/app/app/scripts.py", line 594, in posters4k
> get_audio()
> File "/app/app/scripts.py", line 119, in get_audio
> m = MediaInfo.parse(file, output='JSON')
> File "/usr/local/lib/python3.9/site-packages/pymediainfo/__init__.py", line 494, in parse
> raise FileNotFoundError(filename)
> FileNotFoundError: /films/Rat Race (2001)/Rat Race (2001).mp4

**Comment by jkirkcaldy** [comment]
`/films` should be the mount point that you pass through to the docker container. 
`Movies` is your library. They are different things. 

What does your docker run command look like? Or the Unraid docker settings?

**Comment by KrunchMuffin** [comment]
ahhh makes sense, but I don't the option in the config

![image](https://user-images.githubusercontent.com/1037197/145074866-59263a98-0eeb-4502-878a-ada04237f007.png)

`/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='plex-utills' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'TZ'='America/Toronto' -e 'PUID'='99' -e 'PGID'='100' -p '7777:80/tcp' -v '/mnt/user/PlexMetaData/Media/':'/films':'rw' -v '/mnt/user/appdata/plex-utills/':'/config':'rw' -v '/mnt/user/appdata/plex-utills/':'/logs':'rw' 'jkirkcaldy/plex-utills'
0cda103418679a357232e1a5d9ca14e96db4d3612751d2c62d1be4ec733e97d4`

I see the mount, I guess cause it's not listed in the config as such, it was confusing. I should be able to work it out. THanks.

**Comment by jkirkcaldy** [comment]
Try the Help page and see if that gives you any more information.

**Comment by KrunchMuffin** [comment]
it doesn't, but the config for plex library does. unraid will usually show the mapped container folder path, but I guess comments overrides it.

![image](https://user-images.githubusercontent.com/1037197/145076621-8b705f7d-bdc8-45f6-8863-3d71446613a6.png)

**Comment by jkirkcaldy** [comment]
Assuming that you have all your media in the `/mnt/user/PlexMetaData/Media` directory it should work. 

> FileNotFoundError: /films/Rat Race (2001)/Rat Race (2001).mp4
This looks like it can't find the media. If you go into the console of the container and do `ls /films` what shows up?

**Comment by KrunchMuffin** [comment]
all good.  thanks. I had wrong path.
