### ISSUE TITLE
"Restore posters" script doesn't work unless your library is named "Films"

### ISSUE THREAD

**Issue by KnifeFed** [jkirkcaldy/plex-utills#71]
```
today at 9:52:23 PMException in thread Thread-1:
today at 9:52:23 PMTraceback (most recent call last):
today at 9:52:23 PM  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
today at 9:52:23 PM    self.run()
today at 9:52:23 PM  File "/usr/local/lib/python3.9/threading.py", line 910, in run
today at 9:52:23 PM    self._target(*self._args, **self._kwargs)
today at 9:52:23 PM  File "/app/app/scripts.py", line 772, in restore_posters
today at 9:52:23 PM    films = plex.library.section('Films')
today at 9:52:23 PM  File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 67, in section
today at 9:52:23 PM    raise NotFound('Invalid library section: %s' % title) from None
today at 9:52:23 PMplexapi.exceptions.NotFound: Invalid library section: Films
```

It's hardcoded here:

https://github.com/jkirkcaldy/plex-utills/blob/740a4b8b2108025931cf03b6225423394f80af26/app/scripts.py#L772

**Comment by wgstarks** [comment]
/films is just the container path for the app. You need to point the host path to your actual video library. And in the app settings you set films library to whatever you have named those videos in Plex.

**Comment by KnifeFed** [comment]
That's not the issue here. As you can see in the file I linked, the restore script specifically is hardcoded to use a Plex library called "Films". The other scripts use `films = plex.library.section(config[0][3])`, i.e. the name you configure in the settings.

**Comment by wgstarks** [comment]
My bad. Totally missed the title.😁

**Comment by jkirkcaldy** [comment]
Got it, I think this was left in from a test. 

Fixed now, update coming shortly.
