### ISSUE TITLE
[Errno 2] No such file or directory: '/tmp/<name of movie>_poster.png'

### ISSUE THREAD

**Issue by KnifeFed** [jkirkcaldy/plex-utills#72]
I just ran the latest script and got a bunch of these errors:

```
today at 11:02:53 PM2021-12-07 23:02:53,369 - plex-utills - [Errno 2] No such file or directory: '/tmp/<name of movie>_poster.png'
today at 11:02:53 PM2021-12-07 23:02:53,370 - plex-utills - 4k Posters: Movies The 4k poster for this film could not be created.
today at 11:02:53 PM2021-12-07 23:02:53,370 - plex-utills - This is likely because poster backups are enabled and the script can't find or doesn't have access to your backup location
```

One of them was for "Superman/Batman: Public Enemies" and it said the filename was `Superman/Batman:_Public_Enemies_poster.png`, i.e. the forward-slash and colon weren't replaced. The others didn't contain any illegal characters though.

**Comment by UniverseXXX** [comment]
I've got a similar issue.

**Comment by UniverseXXX** [comment]
@jkirkcaldy Films are ok, TV series posters are not being created. Thx.

**Comment by jkirkcaldy** [comment]
TV posters are created on episodes not on series. Can you confirm that this is not working?

**Comment by KnifeFed** [comment]
> Does the poster get created for you at all?

The only poster that wasn't created was the one with illegal characters, so that makes sense.

What the others have in common is that they all lack HDR, for one of two reasons:
1. They're WEB DV without HDR fallback. These are the exact same 4 + 1 that I [mentioned](https://github.com/jkirkcaldy/plex-utills/issues/65#issuecomment-988286793) in #65
2. They're 4K SDR. These all got HDR banners, as I mentioned in #73

**Comment by jkirkcaldy** [comment]
> > Does the poster get created for you at all?
> 
> The only poster that wasn't created was the one with illegal characters, so that makes sense.
> 
> What the others have in common is that they all lack HDR, for one of two reasons:
> 
>     1. They're WEB DV without HDR fallback. These are the exact same 4 + 1 that I [mentioned](https://github.com/jkirkcaldy/plex-utills/issues/65#issuecomment-988286793) in [[Request] Extend Dolby Vision detection #65](https://github.com/jkirkcaldy/plex-utills/issues/65)
> 
>     2. They're 4K SDR. These all got HDR banners, as I mentioned in [4K SDR movies get HDR banner #73](https://github.com/jkirkcaldy/plex-utills/issues/73)

I've figuired out some of the bugs you reported. It's easier to get them all working before pushing a fix. 

Just working on removing all special characters at the moment.

**Comment by UniverseXXX** [comment]
Not sure if it's related, but I'm getting this error:

```
2021-12-08 17:30:46,043 - plex-utills - 4k Posters: Backup file exists, skipping

Exception in thread Thread-1:

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner

    self.run()

  File "/usr/local/lib/python3.9/threading.py", line 910, in run

    self._target(*self._args, **self._kwargs)

  File "/app/app/scripts.py", line 642, in posters4k

    posterTV_4k()

  File "/app/app/scripts.py", line 586, in posterTV_4k

    get_TVposter()

  File "/app/app/scripts.py", line 524, in get_TVposter

    background = background.resize(size,Image.ANTIALIAS)

UnboundLocalError: local variable 'background' referenced before assignment
```

**Comment by jkirkcaldy** [comment]
This is fixed in the next update. Should be release in the next few hours.

**Comment by jkirkcaldy** [comment]
> This bug occurs for me as well, with 4K SDR TV Shows. The posters aren't created at all and I get the error msg OP posted.

FYI, you can run the 4k TV posters script by going to http://<plex_utills_ip>/tvposters4k

It will still run with the rest of the 4k posters if scheduled. But this way you can test that they are working/run the script manually.

**Comment by saladm2** [comment]
Thanks! New update fixed it for me!
