### ISSUE TITLE
4K SDR movies get HDR banner

### ISSUE THREAD

**Issue by KnifeFed** [jkirkcaldy/plex-utills#73]
After running the latest script, all my 4K SDR movies got an HDR banner. Plex does not show them as being HDR. After running `/api/data` they all say `Unknown` in the `HDR version` column.

**Comment by jkirkcaldy** [comment]
Fixed in dev, rollout coming in the next few days once https://github.com/jkirkcaldy/plex-utills/issues/65 is sorted
