### ISSUE TITLE
[Request] HDR/Dolby Vision detection for TV episodes

### ISSUE THREAD

**Issue by KnifeFed** [jkirkcaldy/plex-utills#77]
After running the latest version on my TV library, none of the episodes got HDR/DV banners, just the 4K banner. It works great for movies but is this intended to be working for episodes as well in the latest image?

**Comment by jkirkcaldy** [comment]
Tv posters only get 4k banners currently. 

 

From: KnifeFed ***@***.***> 
Sent: 13 December 2021 20:44
To: jkirkcaldy/plex-utills ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jkirkcaldy/plex-utills] HDR/Dolby Vision detection doesn't work for TV episodes (Issue #77)

 

After running the latest version on my TV library, none of the episodes got HDR/DV banners, just the 4K banner. It works great for movies but is this intended to be working for episodes as well in the latest image?

**Comment by KnifeFed** [comment]
Ah, ok. Then this is a request instead :)

**Comment by tchirou** [comment]
+1 !!!
Just installed the script thinking it would do it
I hope it can be added

**Comment by tchirou** [comment]
Hi @jkirkcaldy 
Do you think this feature could be added on your roadmap ?
a lot of tv episodes are now in hdr or Dolby vision and it would be nice to have these banners to make sure sonarr downloaded the right file without having to manually check the file
Thanks a lot

**Comment by jkirkcaldy** [comment]
yes, I plan to spend a bit of time giving some love to TV posters. Just working through the issues for the film posters at the moment.

**Comment by jkirkcaldy** [comment]
Completed
