### ISSUE TITLE
Restore doesn't work for TV episodes

### ISSUE THREAD

**Issue by KnifeFed** [jkirkcaldy/plex-utills#78]
After running the latest version on my TV library and none of the episodes got HDR/DV banners, only 4K banners (see #77), I tried restoring them. It only restored movie posters and then said it had been completed.

However, it wouldn't have worked anyway because I noticed that in each season folder there's only a single image, `poster_bak.png`, which is the poster for the first episode.

How do I reset all the episode posters now? I cleared `Plex Media Server/Plug-in Support/Caches` and refreshed all metadata but the posters didn't change.

**Comment by jkirkcaldy** [comment]
This should now all work in new update.
