### ISSUE TITLE
If "Restore from TMDb" is enabled when restore is run, every single poster is changed

### ISSUE THREAD

**Issue by KnifeFed** [jkirkcaldy/plex-utills#79]
When I first ran restore, all movie posters were restored from their backups. When I ran it again because I was trying to restore TV episode posters (see #78), it proceeded to download a new poster for _every single movie_ in my library. As you can imagine, this took forever. Are there no database entries to keep track of which movie posters have been previously altered? 

Also, now every poster is a low-res 600x900 version, even though that's not even a resolution that exists on the TMDB page, e.g. [here](https://www.themoviedb.org/movie/333371-10-cloverfield-lane/images/posters). I cleared `Plex Media Server/Plug-in Support/Caches` and refreshed all metadata but the posters didn't change. 
~~Now I have no idea how to get the full resolution posters back, except for changing them all manually.~~ 
Ok, that part was easy enough, I just changed `poster_url_base` in `scripts.py` to `https://www.themoviedb.org/t/p/original`. Apparently `w600_and_h900_bestv2` ["is not officially supported and may stop working at any time"](https://www.themoviedb.org/talk/5d1ccbd555b0c01c356ae6b8#5d1cf35ca13533000f075c01).

**Comment by KnifeFed** [comment]
Btw, in [`video.guids[1]`](https://python-plexapi.readthedocs.io/en/latest/modules/video.html) you have the TMDB ID, so you don't have to search by name/year.

**Comment by jkirkcaldy** [comment]
changed this in the script now, and it now uses the TMDB guid to search. I can't remember why, but when I first tried to do that it would time out after a couple of movies, now it seems to work fine. 

This will be in the next update.

**Comment by KnifeFed** [comment]
Cool, so if you do a restore now it'll only process movies which poster has been altered?

**Comment by jkirkcaldy** [comment]
So it will always look for local backups first. If a local backup doesn't exist it will then look for a poster from the tmdb but it should only replace posters that are 4K, hdr or have atmos/dts:x audio.

**Comment by KnifeFed** [comment]
Ok, that's good. And restoring TV posters will be a separate script?

**Comment by jkirkcaldy** [comment]
It will be. I haven't written that yet. That will likely come in the new year.
