### ISSUE TITLE
Error when running from outside /plex-utills directory

### ISSUE THREAD

**Issue by seannymurrs** [jkirkcaldy/plex-utills#8]
If I run the script from within the plex-utills directory using the command `python3 4klibrary.py`, it seems to work fine. If I run it from my home directory using the command `python3 ~/plex-utills/4klibrary.py` I get the following error:

`Traceback (most recent call last):
  File "/home/seannymurrs/plex-utills/4klibrary.py", line 12, in <module>
    server = config_object["PLEXSERVER"]
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'PLEXSERVER'`

**Comment by jkirkcaldy** [comment]
If you run the script from outside the script directory, the script has no idea where to find the config file. 

If you need to run the script like this, you may find it easier to hard-code the variables in the script and forgo the config file. 

e.g.
```
....
baseurl = (server["PLEX_URL"])
# replace everything after the = with the information you put in the config file. 

# becomes:
baseurl = http://10.0.0.1:32400
...
```
