### ISSUE TITLE
[FR] HDR/DV banner at the bottom left/right corner instead of middle

### ISSUE THREAD

**Issue by minititof** [jkirkcaldy/plex-utills#83]
I think it would look way better if the HDR/DV banner was at the bottom left corner (or even the right one) instead of in the middle like it is now. Maybe we could have the option to choose which corner we want the banner to be at? Thanks for the app!

**Comment by jkirkcaldy** [comment]
I did have it at the bottom, but it covered a lot of film titles. One of the things on my roadmap is to upload your own banner designs

**Comment by minititof** [comment]
That would be a good option as well! Then we can place it wherever we see fit.
