### ISSUE TITLE
Docker example incorrect?

### ISSUE THREAD

**Issue by mduijm** [jkirkcaldy/plex-utills#86]
Hi,

trying to run your docker image using docker-compose. From your Dockerhub you provide an example like:

docker run -d -p 5000:5000 -v <your/plex/media>:/films -v <mount/your/logs>:/logs -e TZ=Europe/london -e PUID=1000 -e PGUI=1000 jkirkcaldy/plex-utills

From your Github you say:

Ports
Only Port 80 is required to access the container.

and then this template:

docker run -d --name plex-utills \
-p 80:80 \
-v <your_config_directory>:/config \
-v <your_logs_directory>:/logs \
-v <your_plex_media>:/films \
-e TZ=Europe/London \
-e PUID=1000 \
-e PGID=1000 \
jkirkcaldy/plex-utills

When I run the image I see a listening message on port 5000. So what is the 'internal' port where the app runs on? The external I understand I can change to whatever. 

So what is it?

*:5000 or *:80?

**Comment by jkirkcaldy** [comment]
The gunicorn server runs on port 5000 and nginx runs on port 80. 

you should be using port 80 to connect. You can map and access port 5000 if you want but this should only be done for diagnositic purposes. I'll add this in the documnentation

**Comment by mduijm** [comment]
for me mapping to port 80 didn't work, 5000 seems to work fine. Why is NGINX in the container? I already have a NGINX setup, most users should have it when running plex/radarr/sonarr etc (SWAG). So should be some kind of overkill?

**Comment by wgstarks** [comment]
> for me mapping to port 80 didn't work, 5000 seems to work fine. Why is NGINX in the container? I already have a NGINX setup, most users should have it when running plex/radarr/sonarr etc (SWAG). So should be some kind of overkill?

I run Radarr, Sonarr and Plex. Nginx isn’t a requirement for any of those dockers and I don’t have it installed.

**Comment by jkirkcaldy** [comment]
It's a best practice for the gunicorn webserver. You shouldn't server the gunicorn app through port 5000, that should only be used for dev access. Port 5000 has only been left exposed for testing and troubleshooting purposes.
