### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by mduijm** [jkirkcaldy/plex-utills#87]
Hi,

so all of my *rr and Plex and Tautulli are in dockers, and mounts are working fine. 

My plex has mounts like:

/mnt/movies:/movies
/mnt/series:/tv

And how should I pass this on to Plex-Utills?

I tried:
/mnt/movies:/films

and:
/mnt/movies:/movies

but not working.. .

below example from the help page. Perhaps you can give me a tip? 

Title | A XXX in the XXX
-- | --
/movies/A XXX in the XXX
(2019)/A.XXXin.the.XXX.2019.UHD.BluRay.Remux.2160p.HEVC.HDR.DTS.X.7.1-HiFi.mkv
/films/A XXXin the XXX
(2019)/A.XXX.in.the.XXX.2019.UHD.BluRay.Remux.2160p.HEVC.HDR.DTS.X.7.1-HiFi.mkv

**Comment by jkirkcaldy** [comment]
it should be mounted as /mnt/movies:/films

you can also pass though the entire /mnt directory if you want to use TV show posters too like `/mnt:/films`
