### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Zero0Q** [jkirkcaldy/plex-utills#89]
Can you please help me with this issue, i have installed plex in qnap nas as app and plex-utills in qnap nas docker, plex works fine but plex-utills cant access files.

--------------------------------------------------------------------------------------------------------------------------------------------

Plex-utills Paths in docker:

Volume mapping  
/share/data/appdata/PlexUtills/logs:/logs
  
/share/data/appdata/PlexUtills/config:/config
 
/share/data/media:/films  

Useful information is shown below:
Plex URL | http://192.168.1.169:32400
Plex Path: /share
Films Library: Movies

PLEX PATH: /share/data/media/Movies/8-Bit Christmas (2021) [tt11540284]/8-Bit Christmas (2021) [WEBDL-2160p.10bit.x265.AAC.5.1]-YTS.MX.mkv

PLEX LIBRARY: /films/data/media/Movies/8-Bit Christmas (2021) [tt11540284]/8-Bit Christmas (2021) [WEBDL-2160p.10bit.x265.AAC.5.1]-YTS.MX.mkv

--------------------------------------------------------------------------------------------------------------------------------------------

PLEX APP PATHS:
This is plex media in plex app "/share/data/media/Movies" "/share/data/media/TV Shows"

--------------------------------------------------------------------------------------------------------------------------------------------

Plex-utills log:
/usr/local/lib/python3.9/site-packages/apscheduler/triggers/cron/__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum
/usr/local/lib/python3.9/site-packages/apscheduler/triggers/cron/__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
2022-01-04 18:08:28,116 - SYS - 4K/HDR Posters schedule created for 17:00
2022-01-04 18:08:28,116 - SYS - Auto Collections schedule created for 16:30
[2022-01-04 18:08:28 +1100] [3982] [INFO] Worker exiting (pid: 3982)
[2022-01-04 18:08:28 +1100] [4012] [INFO] Booting worker with pid: 4012
2022-01-04 18:08:29,058 - SYS - Setup Helper: Going though the setup helper.
2022-01-04 18:08:29,113 - SYS - [Errno 2] No such file or directory: "/films/data/media/Movies/The 'Burbs (1989) [tt0096734]/test.txt"
2022-01-04 18:08:29,158 - SYS - Updater: Your plexpath has been changed to /share
2022-01-04 18:08:29,182 - SYS - Updater: Your plexpath has been changed to /share
/usr/local/lib/python3.9/site-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
/usr/local/lib/python3.9/site-packages/apscheduler/triggers/cron/__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum
/usr/local/lib/python3.9/site-packages/apscheduler/triggers/cron/__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
2022-01-04 18:08:29,233 - SYS - 4K/HDR Posters schedule created for 17:00
2022-01-04 18:08:29,234 - SYS - Auto Collections schedule created for 16:30

**Comment by jkirkcaldy** [comment]
What are the permissions for the media folder in the plex-utills? 

It needs full read/write access.

**Comment by Zero0Q** [comment]
When I created docker I added read/write, how can I check that. Also if I run ls /films I get this
![Uploading image.jpg…]()

**Comment by Zero0Q** [comment]
Also I have Radarr sonarr Plex with same path in same place in dockers and they all can access the path without any issues

**Comment by Zero0Q** [comment]
![image](https://user-images.githubusercontent.com/20936968/148074410-cf865799-1709-43a0-9634-1534ffd78eeb.jpg)
![Uploading image.jpg…]()

**Comment by Zero0Q** [comment]
Everything is read/write
![image](https://user-images.githubusercontent.com/20936968/148074604-c1c66771-ecb7-4a9d-b67c-d6ef4cbed15c.jpg)

**Comment by jkirkcaldy** [comment]
I don't have a qnap system to test, but something is going wonkey as you have mounted it correctly as far as I can tell. Mounting it as `/share/data/media:/films` should work. And even if it didn't it should still let you perform `ls /films` from the terminal of the container. 

Can you delete the image completely and try pulling it again? Also are you using the plex-utills:latest container?

**Comment by Zero0Q** [comment]
I have gave permission to /films with 
“chmod 777 /films”
 now I can see files in  “/films/movies”
 only if I’m in “/films” folder and by doing ls /Movies all files are there but Plex-utills it’s looking for the files in “/films/data/media/Movies” instead it should look in “/films/Movies”

**Comment by Zero0Q** [comment]
Now when I did update the permission is lost again and it can’t access the files when I add same permission like before nothing changes. Do you know how can I add permanent permission to /films sub folders and files

**Comment by Zero0Q** [comment]
I managed to fix it, backup its not working so I disabled it. I’m not sure if permission will be removed when updates occur. 
This is how I did it in docker volume:
chmode -R 777 /films
/share/data/media:/films
/share/data/media/Movies:/films/Movies 
/share/data/media/TV Shows:/films/TV Shows

**Comment by jkirkcaldy** [comment]
Looking very quickly it looks like you may need to change the puid and guid on your docker command
https://www.linuxserver.io/blog/2017-09-17-how-to-setup-containers-on-qnap
This make it look like you need to set puid to 500 and guid to 100 That should mean that you can read/write to the directory. 

You don't need to enable backups but if you like to change your posters then it is recommended. You can restore them without the backup but it will use the default poster from TMDb.

**Comment by Zero0Q** [comment]
My PUID and GUID is at 0 I will try with your recommendation

**Comment by Zero0Q** [comment]
I tried with your recommendation and still same issue, I will just turn off backup until it gets fixed in the future. Thanks
