### ISSUE TITLE
Script Stops

### ISSUE THREAD

**Issue by adznon** [jkirkcaldy/plex-utills#93]
Hello,

Firstly This is a great application, may thanks for creating it, Have been manually adding the 4K posters for a long time now.

I am wondering if you can help me.

Have been able to install the app on UNRaid using the community plugin.

But, when I try to run it, it runs for the first 30 ish and then stops.

There is no error message in either the script log or the application log.

Can you advise anything I can do to rectify ?

Thanks
Adam

**Comment by jkirkcaldy** [comment]
How about the docker log? Click on the icon of the docker container and click logs. You may need to manually set the script going and wait for it to stop. 

The errors often get outputted there. (I'm working on rectifying this)

**Comment by adznon** [comment]
Thanks for the reply.

Nothing in there either, its weird it just seems to hang.

Have included the log from the start if this helps.

![image](https://user-images.githubusercontent.com/44672208/148770258-8abc03b7-35b3-498a-9f3f-f3dbc7a2f34d.png)

![image](https://user-images.githubusercontent.com/44672208/148770563-51e5b6c0-ae44-446c-9781-ef6a4087f02c.png)

**Comment by jkirkcaldy** [comment]
Does it always hang on 3:10 to Yuma?

**Comment by adznon** [comment]
No that was the first page, didnt sent you all the pages (have a big collection) and it currently stops after "After We Fell"

Thought about that before and removed the ones it used to stop on but then it just seem to do one more, its almost like it times out after doing a certain amount.

**Comment by jkirkcaldy** [comment]
And what appears in the docker logs once it stops? nothing?

**Comment by omahajon** [comment]
I'm getting this same issue. Mine is stopping at "The Blind Side". No error message in unraid logs, it just doesn't continue. I got about 15 files in and it seems to keep happening on this movie each time.
<img width="677" alt="Capture" src="https://user-images.githubusercontent.com/59218321/149017411-1e682b8b-8b4c-4ca7-8943-59ed58a44a26.PNG">

**Comment by jkirkcaldy** [comment]
On your docker host, can you run
`docker exec plex-utills /bin/bash -c "python3 dv_test.py <film library> '<film title>'`

Swapping out <film library> and <film title> with your library and the film it stops on. 

Alternatively, I have rewritten how the code works on the dev container so you could pull that and test to see if that works

**Comment by omahajon** [comment]
Sorry - how do I pull the dev container? I'm assuming I just need to adjust the repo? (Currently: jkirkcaldy/plex-utills)
Running the script gives me the following: 
docker exec plex-utills /bin/bash -c "python3 dv_test.py <Movies> '<The Blind Side>'"
/bin/bash: line 1: Movies: No such file or directory

**Comment by omahajon** [comment]
Sorry for the spam of information. So after changing to the dev container and getting stuck on Bohemian Rhapsody I then changed it to only add 4k banners, no HDR, no DoVi, and it's currently on media start with the letter D, so it's farther.

**Comment by jkirkcaldy** [comment]
can you run `docker exec plex-utills /bin/bash -c "python3 dv_test.py Movies 'Bohemian Rhapsody'`

and see what it says?

Also, you can change the log level to debug in the /admin_config page, which gives greater detail as to what it's doing which may help identify why it's not working.

**Comment by omahajon** [comment]
Ran the script you mentioned above, it's been going about 5 minutes with no output. I'll let it run and see where its at. 
<img width="677" alt="Capture" src="https://user-images.githubusercontent.com/59218321/149205228-ad7ad6e3-5ec5-4ef1-a1c3-d2f8fabfb16f.PNG">
Changed log to debug level but going to wait to see if anything comes out of the script previously ran before attempting to run anything within the web GUI.

**Comment by jkirkcaldy** [comment]
It could be a permissions issue. 

If you run:

Can you check the permissions of that film?

**Comment by omahajon** [comment]
> It could be a permissions issue.
> 
> If you run:
> 
> Can you check the permissions of that film?

Ran `ls -al`
drwxrwxrwx 1 nobody users          10 Jan 12 13:41 ./
drwxrwxrwx 1 nobody users       24576 Jan 11 18:51 ../
-rw-rw-r-- 1 nobody users      133734 Jan  8 12:50 Bohemian\ Rhapsody\ (2018)\ [imdb-tt1727824][Bluray-2160p][HDR][10bit][x265][TrueHD\ Atmos\ 7.1]-SWTYBLZ.eng.srt
-rw-rw-r-- 1 nobody users 22523404228 Jan  8 12:59 Bohemian\ Rhapsody\ (2018)\ [imdb-tt1727824][Bluray-2160p][HDR][10bit][x265][TrueHD\ Atmos\ 7.1]-SWTYBLZ.mkv
-rw-r--r-- 1 root   root      1926664 Jan 12 13:41 poster_bak.png

I'm showing other files such as "The Blind Side" and "Blazing Saddles" with the same permissions

**Comment by omahajon** [comment]
I ended up changing all file permissions within my /data/media/movies & /data/media/tv to be 755 to prevent permission issues - still getting stuck only when either HDR banners/Dolby Atmos/DTS:X are enabled, enabling ONLY 4k banners runs through both movies and shows. Oddly enough I am getting stuck on a 1080p movie now that has neither HDR or 4k.
![image](https://user-images.githubusercontent.com/59218321/149634943-6f660e2f-1b21-48fc-9ef6-f3052f012e09.png)

**Comment by jkirkcaldy** [comment]
I think this should be solved now, please re-open if not.
