### ISSUE TITLE
Error on starting HDR Script, nothing happens after

### ISSUE THREAD

**Issue by mduijm** [jkirkcaldy/plex-utills#95]
Hi,

it seems all mapping from docker to the app is now ok, also I can access the app and configure it. However when starting a script I see the following error:

plex-utills    | 2022-01-09 19:44:19,995 - plex-utills - 4k Posters: 4k HDR poster script starting now.
plex-utills    | Exception in thread Thread-1:
plex-utills    | Traceback (most recent call last):
plex-utills    |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
plex-utills    |     self.run()
plex-utills    |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
plex-utills    |     self._target(*self._args, **self._kwargs)
plex-utills    |   File "/app/app/scripts.py", line 1184, in posters4k
plex-utills    |     m = MediaInfo.parse(file, output='JSON')
plex-utills    |   File "/usr/local/lib/python3.9/site-packages/pymediainfo/__init__.py", line 494, in parse
plex-utills    |     raise FileNotFoundError(filename)
plex-utills    | FileNotFoundError: /films/22 vs. Earth (2021)/22.vs.Earth.2021.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-EVO.mkv

This is of course not OK, as the film is inside /films/movies/

The docker-compose is like this:
  plex-utills:
    image: jkirkcaldy/plex-utills
    container_name: plex-utills
    restart: unless-stopped
    volumes:
      - /mnt:/films
      - /home/xxx/docker/plex-utills/config:/config
      - /home/xxx/docker/plex-utills/logs:/log
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 5000:5000

Plex docker-compose is like this:

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - PLEX_CLAIM=xxxx
    volumes:
      - ~/docker/plex/config:/config
      - /mnt/series:/tv
      - /mnt/movies:/movies
      - /mnt/4kmovies:/4kmovies
      - /mnt/4kseries:/4kseries
      - /mnt/personal_movies:/personal_movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

the folder /mnt is like:
4kmovies  4kseries  books  booksdwn  movies  personal_movies  series

Would it be possible to mount multiple folders into plex-utills and define the object from the UI? This makes it more flexible? 

thanks so far!

Martijn

**Comment by jkirkcaldy** [comment]
Ah, this in one of the things that I need to test as I haven't tested where plex has multiple directories mounted at `/`

If you go to /admin_config can you let me know what the Plex File Path and Plex-Utills File Path entries are. 

![image](https://user-images.githubusercontent.com/26098592/148759788-c1fb22f9-ceef-4463-b6c0-695cdc5787f1.png)

Yours should in theory be:
```
Plex File Path 
/
Plex-Utills File Path
/films
```

**Comment by TheFritz01** [comment]
I have a very similar setup and getting pretty much the exact same error.   When you say go to` /admin_config ` where exactly is that located?   

I have the docker media library set to `/mnt/user/data/media` 

When I drop to the Docker Console I can browse to `/films/media/movies` and I see my library located there.  However, I am still getting the error below. 

`2022-01-31 23:25:24,196 - plex-utills - 4k Posters: 4k HDR poster script starting now.
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/app/app/scripts.py", line 1184, in posters4k
m = MediaInfo.parse(file, output='JSON')
File "/usr/local/lib/python3.9/site-packages/pymediainfo/__init__.py", line 494, in parse
raise FileNotFoundError(filename)
FileNotFoundError: /films/media/movies/100% Wolf (2020)/100% Wolf 2020 Bluray-1080p.mkv`
