### ISSUE TITLE
Error with accented capital character

### ISSUE THREAD

**Issue by tchirou** [jkirkcaldy/plex-utills#96]
Hi
The script stops with a new movie "Eternals". In french in plex, it's "Les Éternels". With an accented capital E.
I changed in plex with the english name and ran the script again, and it worked this time.
Thanks

**Comment by jkirkcaldy** [comment]
How is it saved on disk? 

Currently there is only english language support but if there is an easy fix I don't mind adding it.

**Comment by tchirou** [comment]
It’s saved as eternals
Maybe you could use the real filename instead of the library name ?

**Comment by jkirkcaldy** [comment]
ok the new dev container has a potential fix for this now. 

The scripts will simply swap out an accented character for an non accented character. 

Though it shouldn't actually matter as all the data is taken from plex.

**Comment by tchirou** [comment]
Ok so do you want me to install a new image with dev to test it out ?

**Comment by jkirkcaldy** [comment]
Sure. That would help

I changed the name of it in my library and tested and it worked.

**Comment by tchirou** [comment]
Will do and report back tomorrow
Thanks a lot

**Comment by tchirou** [comment]
Hi
I removed the movie, removed the poster_bak, added again the movie, changed the metadata in french and ran the script and it worked. Thanks
One thing though : yesterday i had an hdr file. This morning I got the dolby vision file. Before running the dev instance, the master ran and i got
![image](https://user-images.githubusercontent.com/6749420/149174818-a3f71012-9738-4957-8436-79bf75f7048a.png)
And the script stopped
Have you ever encountered this situation ?
Should i open a new ticket ?
Thanks a lot for everything

**Comment by jkirkcaldy** [comment]
So the file hasn't changed but yesterday on the master file you got a HDR banner and today on the Dev container you got a dolby vision banner?

**Comment by tchirou** [comment]
Yes, I manually upgraded the file this morning from an hdr one to a dv one. Plex utills master detected the change when running the script, tried to add or change the hdr banner to the dv one and just hanged
Didn’t try with dev as the file already was a dv one.
Sorry I wasn’t clear enough

**Comment by jkirkcaldy** [comment]
Ok, I'll have a look and see what the issue could be.
