### ISSUE TITLE
Adding /films to the beginning of my media directory.

### ISSUE THREAD

**Issue by jlyfshhh** [jkirkcaldy/plex-utills#99]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/57607562/150237990-9e4cbedf-a33e-49c1-99c0-ced2efb32a89.png">

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/57607562/150238154-0b05a4fa-1611-4923-9b66-e371931f36f9.png">

The Plex Path is correct for how Plex sees my media. The Plex-utills path is correct but for some reason adds /films to the beginning and this causes it not to run correctly.

**Comment by jkirkcaldy** [comment]
It adds `/films` because that's where you mount all your media in the plex-utills container so the scripts take the path that plex sees and translates it into a path that it can see. 

`docker exec plex-utills /bin/bash -c "ls /films"` should return the exact same result of `docker exec <plex docer container> /bin/bash -c "ls /Volumes"`

**Comment by jlyfshhh** [comment]
If I pass /volume1/data/media to the container as /films then the path should be /films/movies/12 Strong right? Why is /data/media being included? I don't understand what I am supposed to mount for the container.

**Comment by jkirkcaldy** [comment]
You need to manually change the plexpath inside the container. 

The script takes the location of your file as plex sees it and then tries to translate it to what the script sees. So your mount for `/films` should match what you pass through to your plex container. 

In your case, leaving everything as is, you can use the manual override function. Currently this is only in the :dev container. 

To do this, go to the /admin_config page on your plex-utills webui. Then there is the option to manually change the plexpath. 

Set this to True and change the override box to say `/Volumes/data/media` this should then map the path correctly.
